monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists
        - jwt
        - security
        - request

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
                channels: ["!event"]

            # Console logging for development
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine", "!console"]

            # JWT specific logging
            jwt:
                type: stream
                path: "%kernel.logs_dir%/jwt.log"
                level: debug
                channels: ["jwt"]

            # Security logging
            security:
                type: stream
                path: "%kernel.logs_dir%/security.log"
                level: debug
                channels: ["security"]

            # Request logging
            request:
                type: stream
                path: "%kernel.logs_dir%/request.log"
                level: debug
                channels: ["request"]

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                channels: ["!event"]
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug

when@prod:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [404, 405]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: "%kernel.logs_dir%/%kernel.environment%.log"
                level: debug
            console:
                type: console
                process_psr_3_messages: false
                channels: ["!event", "!doctrine"]
