<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJQYFvmQ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJQYFvmQ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJQYFvmQ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJQYFvmQ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJQYFvmQ\App_KernelDevDebugContainer([
    'container.build_hash' => 'JQYFvmQ',
    'container.build_id' => '3eb14bcb',
    'container.build_time' => 1756799939,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJQYFvmQ');
